# Azure Deployment Configuration
# Update these values according to your Azure environment

# Resource Group
resourceGroup: "dynatrace-cicd-rg"
location: "East US"

# Azure Container Registry
acrName: "dynatracecicdacr"
acrSku: "Basic"

# Azure Database for PostgreSQL (Cost-optimized for testing)
postgresServerName: "dynatrace-cicd-postgres"
postgresAdminLogin: "dynatraceadmin"
postgresAdminPassword: "Dynatrace2025!"
postgresDatabaseName: "ecommerce"
postgresSku: "B_Gen5_1"  # Basic tier, 1 vCore, 2GB RAM

# Azure Kubernetes Service (Cost-optimized for testing)
aksClusterName: "dynatrace-cicd-aks"
aksNodeCount: 1  # Reduced from 2 to 1 node
aksVmSize: "Standard_B1s"  # Smaller VM: 1 vCPU, 1GB RAM (was B2s: 2 vCPU, 4GB RAM)
aksVersion: "1.28"

# Application Configuration
appNamespace: "dynatrace-cicd"
appName: "ecommerce-demo"

# Dynatrace Configuration (Update with your values)
dynatraceEnvironmentId: "YOUR_DYNATRACE_ENVIRONMENT_ID"
dynatraceApiToken: "YOUR_DYNATRACE_API_TOKEN"
dynatraceTenantId: "YOUR_DYNATRACE_TENANT_ID"

# Domain Configuration (Optional - for custom domain)
customDomain: "your-domain.com"
sslCertName: "dynatrace-cicd-ssl"
