# Staging Environment
environment:
  name: "staging"
  identifier: "staging"
  orgIdentifier: "default"
  projectIdentifier: "dynatrace_demo"
  description: "Staging environment for testing and validation"
  type: "PreProduction"
  tags:
    environment: "staging"
    purpose: "testing"
  variables:
    - name: "DATABASE_URL"
      type: "String"
      value: "postgresql://postgres:password@staging-postgres:5432/ecommerce"
    - name: "REDIS_URL"
      type: "String"
      value: "redis://staging-redis:6379"
    - name: "LOG_LEVEL"
      type: "String"
      value: "debug"
  overrides:
    manifests:
      - manifest:
          identifier: "ecommerce-manifests"
          type: "K8sManifest"
          spec:
            store:
              type: "Git"
              spec:
                connectorRef: "github_connector"
                gitFetchType: "Branch"
                paths:
                  - "k8s/staging/"
                branch: "main"

---
# Production Environment
environment:
  name: "production"
  identifier: "production"
  orgIdentifier: "default"
  projectIdentifier: "dynatrace_demo"
  description: "Production environment for live application"
  type: "Production"
  tags:
    environment: "production"
    purpose: "live"
  variables:
    - name: "DATABASE_URL"
      type: "String"
      value: "postgresql://postgres:password@production-postgres:5432/ecommerce"
    - name: "REDIS_URL"
      type: "String"
      value: "redis://production-redis:6379"
    - name: "LOG_LEVEL"
      type: "String"
      value: "info"
  overrides:
    manifests:
      - manifest:
          identifier: "ecommerce-manifests"
          type: "K8sManifest"
          spec:
            store:
              type: "Git"
              spec:
                connectorRef: "github_connector"
                gitFetchType: "Branch"
                paths:
                  - "k8s/production/"
                branch: "main"
