service:
  name: "ecommerce-service"
  identifier: "ecommerce_service"
  orgIdentifier: "default"
  projectIdentifier: "dynatrace_demo"
  description: "E-commerce microservices application for Dynatrace CI/CD automation testing"
  tags:
    service: "ecommerce"
    environment: "demo"
  serviceDefinition:
    type: "Kubernetes"
    spec:
      manifests:
        - manifest:
            identifier: "ecommerce-manifests"
            type: "K8sManifest"
            spec:
              store:
                type: "Git"
                spec:
                  connectorRef: "github_connector"
                  gitFetchType: "Branch"
                  paths:
                    - "k8s/"
                  branch: "main"
              skipResourceVersioning: false
              enableDeclarativeRollback: false
      variables:
        - name: "imageTag"
          type: "String"
          description: "Docker image tag for deployment"
          value: "<+pipeline.sequenceId>"
        - name: "replicaCount"
          type: "Number"
          description: "Number of replicas for each service"
          value: 2
        - name: "environment"
          type: "String"
          description: "Target environment"
          value: "production"
      artifacts:
        primary:
          primaryArtifactRef: "<+input>"
          sources:
            - spec:
                connectorRef: "docker_hub_connector"
                imagePath: "your-dockerhub"
                tag: "<+input>"
              identifier: "frontend"
              type: "DockerRegistry"
            - spec:
                connectorRef: "docker_hub_connector"
                imagePath: "your-dockerhub"
                tag: "<+input>"
              identifier: "api-gateway"
              type: "DockerRegistry"
            - spec:
                connectorRef: "docker_hub_connector"
                imagePath: "your-dockerhub"
                tag: "<+input>"
              identifier: "user-service"
              type: "DockerRegistry"
            - spec:
                connectorRef: "docker_hub_connector"
                imagePath: "your-dockerhub"
                tag: "<+input>"
              identifier: "product-service"
              type: "DockerRegistry"
            - spec:
                connectorRef: "docker_hub_connector"
                imagePath: "your-dockerhub"
                tag: "<+input>"
              identifier: "order-service"
              type: "DockerRegistry"
            - spec:
                connectorRef: "docker_hub_connector"
                imagePath: "your-dockerhub"
                tag: "<+input>"
              identifier: "payment-service"
              type: "DockerRegistry"
