apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynatrace-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy first
spec:
  project: default
  
  source:
    repoURL: https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/main/config/helm/repos/stable
    chart: dynatrace-operator
    targetRevision: v1.3.0
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dynatrace
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10