apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: dynatrace-cicd
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: order-service
          image: dynatracecicdacr.azurecr.io/order-service:latest
          ports:
            - containerPort: 3003
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_URL
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:3004"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3002"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: dynatrace-cicd
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http

