apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: dynatrace-cicd
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: api-gateway
          image: dynatracecicdacr.azurecr.io/api-gateway:latest
          ports:
            - containerPort: 4000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: USER_SERVICE_URL
              value: "http://user-service:3001"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3002"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:3003"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:3004"
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: dynatrace-cicd
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: 4000
      protocol: TCP
      name: http

