apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: dynatrace-cicd
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: payment-service
          image: dynatracecicdacr.azurecr.io/payment-service:latest
          ports:
            - containerPort: 3004
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: dynatrace-cicd
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 3004
      targetPort: 3004
      protocol: TCP
      name: http

